### ISSUE TITLE
Add New Statistics Screen

### ISSUE THREAD

**Issue by AdilHajiyev** [AdilHajiyev/groupproject-team-1-spacey#2]
This screen will be showing statistics of the level/levels, like how many times did the player shoot projectiles, how many of them did the player hit, how many times did enemies shoot and how many did they hit.

To do this first we will need to make a function and add different variables that will increase when there is shooting and hitting, for both enemies and player. Then we will need to call these in functions like singlePlayerFire, enemyFire, singlePlayerObjHit, and so on, so the variable values increase as we trigger those functions. Then we will need to store those values and put an option to see the statistics screen at the end of each level.

**Comment by onzfonz** [comment]
I think this is good, but would want you to store those values and give folks the option to clear them

**Comment by onzfonz** [comment]
so work on this one!
